language: python
sudo: false
cache: pip
python:
  - 2.7

addons:
  apt:
    packages:
      - expect-dev
      - python-lxml
      - python-simplejson
      - python-serial
      - python-yaml

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

matrix:
  - LINT_CHECK="1"
