language: python
sudo: false
cache: pip
python:
  - 2.7

addons:
  apt:
    packages:
      - expect-dev
      - python-lxml
      - python-simplejson
      - python-serial
      - python-yaml

env:
  global:
  - VERSION="10.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

matrix:
  - LINT_CHECK="1"

install:
  - git clone --depth=1 https://github.com/Elico-Corp/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

virtualenv:
  system_site_packages: true
